### ISSUE TITLE
New feature on the project

### ISSUE THREAD

**Issue by ElefthManolis** [yangshun/2048-python#21]
Hi community,
i want to contribute to this project and i have an idea to implement a machine learning algorithm to help the player for the next move on the game. Do you like it? I'm waiting your response.

Regards,
Manos

**Comment by yangshun** [comment]
Hi I think this is a cool idea but maybe it should be a separate project as this is a Python project targeted at beginners and implementing AI would be out of scope. Also, you don't need machine learning for next move recommendations, basic AI techniques would suffice.

**Comment by ElefthManolis** [comment]
I had the thought to do a button in the GUI for 'Help' and with a simple algorithm implementation (e.g. BFS), suggest the player the next move. Is this fit on the project?
